version: '2'
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
#           - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus           
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'   
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention=24h'     
        mem_limit: 512000000

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        ports:
            - '9100:9100'
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
            - /etc/hostname:/etc/host_hostname
        command: 
            - '--path.procfs=/host/proc' 
            - '--path.sysfs=/host/sys'
            - --collector.filesystem.ignored-mount-points
            - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=password
        volumes:
           - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
        ports:
          - "3000:3000"

    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        ports:
            - "8088:8080"
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro

    alertmanager:
        image: prom/alertmanager:latest
        container_name: alertmanager
        volumes: 
          - ./alertmanager/:/etc/alertmanager/
          - ./prometheus:/prometheus
        command:
          - '--config.file=/etc/alertmanager/config.yml'
#          - '--storage.path=/alertmanager'
        ports:
          - '9093:9093'

volumes:
        prometheus_data: {}
        grafana_data: {}
