groups:
- name: node.rules
  rules:
  - alert: Down
    expr: up == 0
    for: 5m
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "Instance {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

